yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@jimp/utils@*":
    dependencies:
      "regenerator-runtime": "*"
  "@expo/webpack-config@*":
    dependencies:
      "tapable": "*"
      "fork-ts-checker-webpack-plugin": "*"
  "@unimodules/core@*":
    dependencies:
      "@unimodules/react-native-adapter": "*"
  "expo@*":
    dependencies:
      "fbjs": "*"
  "expo-font@*":
    dependencies:
      "@unimodules/core": "*"
  "expo-image-picker@*":
    dependencies:
      "@unimodules/core": "*"
      "unimodules-permissions-interface": "*"
  "expo-linking@*":
    dependencies:
      "@unimodules/core": "*"
      "fbjs": "*"
  "expo-splash-screen@*":
    dependencies:
      "@unimodules/core": "*"